### ISSUE TITLE
[Production] Organize Level File Directories

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#118]
Repository contains folders at same level of directory hierarchy:

* Game/Content/OpenTournament/Levels
* Game/Content/OpenTournament/Levels_Experiments
* Game/Content/OpenTournament/Levels_Shells

Makes no sense to have these folders present in this way, rather than

* Game/Content/OpenTournament/Levels
* Game/Content/OpenTournament/Levels/Experiments
* Game/Content/OpenTournament/Levels/Shells

**Comment by Saibamen** [comment]
Pushed into master branch. Please retest

**Comment by wail** [comment]
Finally seems to have eliminated Levels_Shells.
