### ISSUE TITLE
[Production] Webpage Redesign

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#12]
- [ ] Clean Up HTML / JS / CSS
- [ ] Improve Visual Direction / Branding
- [ ] Social Media Feed
- [ ] Concept Art Gallery
- [ ] Other

**Comment by HeXx123321** [comment]
Access to project files?

**Comment by OpenTournament** [comment]
Will have to create some kind of authorized access to the FTP / Webserver. How best to contact you about this?

**Comment by HeXx123321** [comment]
Yeah FTP could work. Private email?

**Comment by HeXx123321** [comment]
info@psybrtech.co.za

**Comment by Saibamen** [comment]
What frameworks/libraries do we use?
