### ISSUE TITLE
[Design][Code] Movement: Crouch sliding

### ISSUE THREAD

**Issue by Niklot-OT** [OpenTournament/OpenTournament#148]
- [ ]  Create a high level concept design document for the feature
- [ ]  Concept approval
- [ ]  First implementation pass, document formula, mechanics and distances
- [ ]  QA Pass and tweaking

**Comment by Niklot-OT** [comment]
![q4crouchslidereference](https://user-images.githubusercontent.com/69342034/92466863-060a0400-f1d1-11ea-9825-1839df3d1cf0.gif)

**Comment by wail** [comment]
Closing issue here, pending discussion in OT-#203
