### ISSUE TITLE
[Design][Code][Discussion] Weapon groups settings

### ISSUE THREAD

**Issue by ChatouilleGG** [OpenTournament/OpenTournament#154]
I came up with the following idea for providing players with a way to configure their weapon bar, with keybindings, including optional grouping and piped weapon switches. All in one.

The configuration would be held in an array of structures like this :
```
structure WeaponGroup
{
    Weapons = array of weapon classes
    Display = true/false
    Keybind (optional)
}
```

User can define (via options menu) *any* number of weapon groups.

User specifies whether a weapon group should be displayed or not (on weapon bar). If there are multiple weapons in the group, they would show up grouped like they usually do in UT series.

User can specify an optional keybind to switch to weapon of that group. If there are multiple weapons in the group, game rotates weapons in configured order.

A weapon can be contained in multiple groups, making it possible to set up weapon bar in a specific way while setting up keybinds in a completely different way (with invisible groups).

Mod-weapons would fall back by default to the configuration of their parent. After which they should show up in settings for custom configuration if desired. If necessary, rather than using parent, we can add a weapon property to let mod-weapons specify which weapon class to fall back to (ie. which weapon it is the most alike to).

**Comment by wail** [comment]
This seems like a promising approach, little bit fuzzy on the mod-weapons having a reference to existing weapons however ultimately we can refine as needed once a prototype is established.

**Comment by wail** [comment]
I think this is also complete. @ChatouilleGG confirm?

**Comment by ChatouilleGG** [comment]
👍

**Comment by wail** [comment]
Closing as complete
