### ISSUE TITLE
Game Events Feed (Kill Feed) System

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#199]
Game Events Feed displays Game Events.

Examples:
![image](https://user-images.githubusercontent.com/604328/103459342-b1891800-4cdc-11eb-8e88-5e04ab646907.png)

![image](https://user-images.githubusercontent.com/604328/103459384-0c227400-4cdd-11eb-9712-a05f9a6dd5a4.png)

* For purposes of Milestone 1 this should be limited to simple {KillerName} killed {KilledName}
* This may already have some existing support in Communications/Chat window.

**Comment by ChatouilleGG** [comment]
basic kill feed operational
![image](https://user-images.githubusercontent.com/7253541/159683282-41888651-5538-4d15-8257-faef8ad05302.png)

for things like customized messages or weapon icons we will have to implement a variety of DamageTypes. For now all weapons are using base UDamageType class.
