### ISSUE TITLE
[Music] Do you need a musician?

### ISSUE THREAD

**Issue by mrzapp** [OpenTournament/OpenTournament#215]
Very cool project!

Sorry for creating an issue for this here, but the "join the team" form required a Google account, which I don't (intend to) have :sweat_smile: 

I am a long time game developer, but an even longer time musician, and my main inspiration is Alexander Brandon, the composer for the original Unreal Tournament game. I feel like my style would fit this project, so I am offering my services.

[Here](https://jeppez.app/music) is a small taste of what I do.

If I was to contribute my music, it would be all new tracks, and their license would follow the project, I don't intend to be a legal obstruction in any way. I can also collaborate with already involved musicians, if you happen to have some on the project already. If you're interested, let me know. You can just reply to the issue or hit me up here:

![email](https://jeppez.app/img/email.png)

**Comment by wail** [comment]
Hi @mrzapp !

Appreciate you reaching out. Musicians are definitely welcome. @mothershipl is probably the best person to communicate with on the topic of music.

I'm going to close this issue but encourage you to participate in the [discussions](https://github.com/OpenTournament/OpenTournament/discussions) area.
