### ISSUE TITLE
[BUG] EnergyRifle, NovaLance & instagib variants materials issues

### ISSUE THREAD

**Issue by ChatouilleGG** [OpenTournament/OpenTournament#230]
- [x] EnergyRifle instagib variant is drawn behind left hand
![image](https://user-images.githubusercontent.com/7253541/126973081-4675011e-cb1c-42b7-91c8-b5074d7a0045.png)

- [x] NovaLance looks broken in 1p
![image](https://user-images.githubusercontent.com/7253541/126973716-797dd0fe-2c54-4f3b-a775-9347aabec585.png)

- [x] NovaLance instagib variant uses regular color (blue ish) in 3p instead of instagib color (yellow ish)
- [x] NovaLance instagib uses regular beam color (blue ish)
- [x] NovaLance beam rings look broken

**Comment by ChatouilleGG** [comment]
why did this not close ?

**Comment by Niklot-OT** [comment]
I suppose it should be manually closed upon verifying the fix on a cooked build.

**Comment by Niklot-OT** [comment]
Fix verified on Steam (Development) build from unstable branch.

**Comment by Niklot-OT** [comment]
Fix verified on latest Steam build from unstable branch.
Closing the issue.
