### ISSUE TITLE
[BUG] First person view weapons are not properly positioned

### ISSUE THREAD

**Issue by ChatouilleGG** [OpenTournament/OpenTournament#232]
- [ ] Most first person view weapons take too much screen space
- [ ] Most first person view weapons are not aligned towards crosshair. This looks especially bad with beam weapons :

![image](https://user-images.githubusercontent.com/7253541/126975758-e9f35bde-7f87-416f-8b70-a10906e8ca08.png)

![image](https://user-images.githubusercontent.com/7253541/126975765-f8207f51-7dbd-4e59-b9c2-cc7ee5b9bd33.png)

**Comment by Niklot-OT** [comment]
Issue fixed in next PR from Niklot-OT branch.

**Comment by ChatouilleGG** [comment]
I think it's good enough for now. The remaining problem lies in bad muzzle offset due to material panini projection.
