### ISSUE TITLE
[BUG] Customized characters abruptly change their armor and skin colour after being damaged

### ISSUE THREAD

**Issue by Niklot-OT** [OpenTournament/OpenTournament#285]
**Bug Description**
Damaging a character that had their look customized causes their armor and skin to abruptly change between armor and skin color upon camera movement.

**To Reproduce**
1. Start PIE on OpenTournamentEntry map
2. Pick up any non-instagib weapon
3. Shoot the character from the BP_Character_Factory spawner

**Expected Behavior**
The character's colors should stay the same.

**Screenshots or Video**
https://user-images.githubusercontent.com/69342034/230760960-4b340d84-65b3-41f5-928f-4fd088d706d3.mp4

**Additional Information:**
- PR #284

**Additional context**
Issue was tested only in PIE.

**Comment by ChatouilleGG** [comment]
fixed in 01119a2 and aa19ad5ff815e8ec2f67508da28f47c605fa1310
