### ISSUE TITLE
Remove Assets Mistakenly Added to GitHub

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#30]
- [x] SciFiWeaponsDark
- [x] Old Map Shells

**Comment by Saibamen** [comment]
Related https://github.com/OpenTournament/OpenTournament/pull/6, https://github.com/OpenTournament/OpenTournament/commit/01aadb0b3a5bd4be32c2e556bd11a92023a60eb6 and https://github.com/OpenTournament/OpenTournament/commit/3ac3da19fc931fc75b1ddc785d7c48fdbdff3c2d
