### ISSUE TITLE
Remove Assets from Source Repository

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#31]
- [ ] SciFiWeaponsDark
- [x] Old Map Shells
- [ ] 100 MB+ Asset Files

**Comment by Saibamen** [comment]
Duplicate of https://github.com/OpenTournament/OpenTournament/issues/30...

**Comment by vladserbanescu11** [comment]
Closing duplicated issue which is also solved and no longer relevant.
