### ISSUE TITLE
Pending Merges

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#32]
- [x] Merge Vlad-Dev
- [ ] Merge Chatouille Weapon Dev
- [ ] Merge DonMoaskarton Branch
- [ ] Merge into Develop

**Comment by Saibamen** [comment]
Please link to branches, this is open source project and we don't know what you want to merge...

**Comment by vladserbanescu11** [comment]
No longer relevant as the transition to GitHub included reviewing the other branches and merging the relevant files.
