### ISSUE TITLE
Development-Build Distribution Process (Unreal Game Sync)

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#36]
https://www.unrealengine.com/en-US/blog/workflow-on-fortnite-collaboration-on-large-teams-with-unrealgamesync
https://docs.unrealengine.com/en-US/Programming/Deployment/UnrealGameSync/index.html

Problem:
Designers & Content Developers in Open Tournament need to be able to quickly pull down latest changes, without having to become deeply invested into an Engineering workflow (Building in Visual Studio, etc).

Solution:
Unreal Game Sync. Used by Epic Games to quickly distribute development to their worldwide content development teams.

What's Needed:
Investigate Unreal Game Sync. Develop a roadmap for using Unreal Game Sync in Open Tournament.

**Comment by vladserbanescu11** [comment]
I investigated this, starting with the paper linked at the top.

- It relies entirely on the premise that projects are distributed and developed with a custom engine attached to them.
- It's built to work with Perforce, not Git.
- It's aimed to help people working on multiple projects at the same time, all using Perforce.

**Comment by vladserbanescu11** [comment]
No longer relevant as the recent automation work solves this issue.
