### ISSUE TITLE
Convert OpenTournament user into OpenTournament organization

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#60]
GitHub's Organization structure provides useful and valuable tools to help OT project management. We should convert OpenTournament user into an organization.

- [x] Create OpenTournamentTeam 
- [x] OpenTournamentTeam ownership change
- [ ] Convert OpenTournament into organization
- [ ] Migrate OpenTournamentTeam users & threads to OpenTournament organization

**Comment by vladserbanescu11** [comment]
Solved and no longer relevant.
