### ISSUE TITLE
Weapons in the InventoryWeaponTest crash the game on pickup

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#62]
Repro rate: 100% (both for game and PIE)
Repro steps:
1. Boot the game
2. Pick the InventoryWeaponTest level
3. Attempt to pickup any weapon
Please note: When triggered in PIE, the issue crashes the whole Editor unless the game is launched as a separate instance.

**Comment by ChatouilleGG** [comment]
Fixed.

Note that weapons are not meant to be picked up from the ground yet, they should be picked up from weapon bases.

Ground weapons are remnant from a previous implementation, which has been overhauled. This implementation will be re-used and properly tested later on, after implementing weapon drops.

**Comment by Saibamen** [comment]
What is `PIE`?

**Comment by vladserbanescu11** [comment]
> What is `PIE`?

Play-In-Editor
