### ISSUE TITLE
Aqua and Cube38 cannot be picked from the Main Menu

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#63]
Repro rate: 100%
Repro steps:
1. Boot the game
2. Open the level choosing dropdown in the main menu
3. Notice that the two aforementioned maps are not present in the dropdown

**Comment by ChatouilleGG** [comment]
Fixed - main menu automatically lists all available maps with /Game/OpenTournament/ prefix

**Comment by Saibamen** [comment]
@ChatouilleGG: Please link to Pull Request/ commit URL where you fixes this
This will help understand newcomers how project is construted etc

**Comment by ChatouilleGG** [comment]
This was fixed before github migration.
