### ISSUE TITLE
[Design][Code][Implementation][Feature] Ammo System

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#74]
Design & Implementation of Ammo System (for lack of a better term)

**Requirements**
* Ammo Pickups
* Allows players to pick up ammo before acquiring a gun
* Supports Mod Weapons
* Supports Weapons that may use more than 1 type of Ammunition

**Comment by ChatouilleGG** [comment]
- Support ammo that can be shared among multiple weapons

Almost done can u assign me to it since i can't :rage1: 
Also label as "feature" maybe or at the very least "enhancement"

**Comment by wail** [comment]
I think this is complete, should probably close?

**Comment by ChatouilleGG** [comment]
👍

**Comment by wail** [comment]
Closing as complete
