### ISSUE TITLE
[Design][Code] HUD Messages

### ISSUE THREAD

**Issue by ChatouilleGG** [OpenTournament/OpenTournament#81]
We need widgets to display messages/announcements on HUD about various game events, such as kills, pickups, end game...

Traditionally, this was done in UT using the LocalMessage class.
A LocalMessage is an abstract class that contains default properties and methods that are either static, or called on the CDO.
When a message is sent from server to client, it is always sent with a Switch (integer), two PlayerState references, and an Object reference.
When a message is received, it is sent to a HUD section according to a category property (game announcements, kill messages, pickup messages etc.) and stored for later display (in case there is a queue).

The current LocalMessage framework has zero Blueprints support in UE4.
If you look at LocalMessage.cpp you can see that it is, basically, nothing.

I would suggest to ditch entirely the traditional LocalMessage framework, and use a custom tailored approach for each type of event/announcement, involving Event Dispatchers, and providing better mod support.

Example for kill events :
- Add replicated function MulticastKillEvent(PlayerState Victim, PlayerState Killer, DamageType) in GameState
- Add event dispatcher KillEventDispatcher in GameState
- Whenever kill occurs, gamemode calls GameState->MulticastKillEvent, which then triggers KillEventDispatcher
- Anything can listen to KillEventDispatcher and react accordingly (eg. HUD kill announcer widget, kill log widget)

Example for pickup messages :
- Add replicated function DispatchPickupEvent(Pickup) in Character
- Add event dispatcher PickupEventDispatcher in Character
- Whenever pickup happens, it calls Character->DispatchPickupEvent, which then triggers PickupEventDispatcher
- Anything can listen to PickupEventDispatcher and react accordingly (eg. HUD pickup message widget)

These methods should help making HUD alot more modular, all while providing a good bunch of new events for mods to listen to, on both server & client sides.

**Comment by wail** [comment]
I'm in favor of migrating away from that system. What you've described sounds robust/extensible to me.

What I envision for the HUD overall is that players can place (or remove) widgets independently of other widgets. In this approach, it seems logical we'd want the widgets themselves to assume responsibility for listening to specific types of events relevant for the data they'd utilize. The type is implicit and doesn't rely on some fixed mapping. I do wonder if there's some limitation I'm not immediately seeing here, but for the time being I see no reason not to pursue this approach.

**Comment by ChatouilleGG** [comment]
Pretty much implemented over time in a variety of commits :
- ddd3e469f70c98d9a00bfa4a1cac5afb84554bd4 removed LocalMessage usages, add frag event, add pickup event, add winner event, hud widgets
- 01d58c48aa10c714946bb73d3cdc5e1169f34f74 proper integration in Pickup/Factory
- 538bc4fb9037427b66e1fa2170e1195d99bf3d94 replace old PickupBase with PickupFactory in Entry map. Other maps still pending
- fd0ed89cc4a3b699a92409ed4e1d0763975258e4 kill feed
