### ISSUE TITLE
Projectile mesh scale is incorrect in parent class

### ISSUE THREAD

**Issue by TamzidFarhan** [OpenTournament/OpenTournament#84]
The static mesh component  in UR_Projectile seems to be scaled up in the parent class.
So any new mesh needs to be scaled way up in projectile bp child class.

A properly scaled new sphere mesh could be imported to fix it.

![image](https://user-images.githubusercontent.com/30652691/89639199-f09e7300-d8ce-11ea-8177-79985e25e2b0.png)

**Comment by ChatouilleGG** [comment]
The base class is UR_Projectile (C++) and it doesn't have any scale.
If you have an inherited scale then you subclassed an existing BP projectile.

**Comment by TamzidFarhan** [comment]
That's right. I've found out the issue was incorrect scaling with my projectile mesh.
I've reimported it proper scale now.
